### ISSUE TITLE
None of the menu commands for copying "tabs in *" works

### ISSUE THREAD

**Issue by hmijail** [kashiif/copy-urls-expert#22] opened 2016-05-23 08:49 UTC
Neither "Tabs in this window", "tabs in all windows", "this tab", etc. seems to work. 
The Browser console shows in each of them:
TypeError: fmtPattern is null
copyUrlsExpert._transform()
 copyurlsexpert.js:425
copyUrlsExpert._copyEntriesToClipBoard()
 copyurlsexpert.js:380
copyUrlsExpert.performCopyTabsUrlWithTemplate()
 copyurlsexpert.js:509
copyUrlsExpert.performCopyTabsUrl()
 copyurlsexpert.js:498
oncommand()
 browser.xul:1

**Comment by hmijail** [comment] 2016-05-23 08:50
Sorry, I forgot: Firefox 47b6, Mac OS X 10.11.5

**Comment by kashiif** [comment] 2016-05-23 11:39
I tried on Mac OSx 10.11.3 and it is working.

What version of extension are you using?

If you are using Copy Urls Expert v2.5.0, can you please check the solution in [this comment](https://github.com/kashiif/copy-urls-expert/issues/20#issuecomment-216391140) and see if it works for you.

**Comment by hmijail** [comment] 2016-05-23 22:04
Yes, I'm in Copy Urls Expert 2.5.0. 
I tried going into the prefs, clicking save and closing, and now it does seem to work. Huh.

Anyway, thanks :).

**Comment by kashiif** [comment] 2016-05-23 22:40
Duplicate of #20

**Closed by kashiif** 2016-05-23 22:40 UTC
Labels: duplicate
