### ISSUE TITLE
Exclude pinned tabs

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#26] opened 2016-12-20 09:33 UTC
I would rather not have my pinned tabs be copied. Can you add an option for it?

**Comment by Keith94** [comment] 2016-12-26 17:05
I just noticed this feature was already present in `Todo.txt`, but let's keep this open for reference.

**Comment by kashiif** [comment] 2016-12-31 00:40
Fixed in ADVANCE-COPY branch

**Comment by kashiif** [comment] 2016-12-31 00:49
@Keith94  Can you please take the code from release-2.6.0 branch and confirm the fixes?

**Comment by Keith94** [comment] 2016-12-31 01:06
So far, that new build won't copy anything for me; this is the error: `TypeError: fmtPattern is null[Learn More]  copy-task.jsm:68:7`

**Comment by kashiif** [comment] 2016-12-31 01:18
This happens when there is an exception during extension initialization. Please follow following:

1. Open developer's console (Ctrl+Shift+J)
2. You may want to clear all the current contents of console window by clicking the recycle bin button at top left corner of the console window.
2. Open a new firfox window (Ctrl + N) and look for any errors reported in developer's console.

**Comment by Keith94** [comment] 2016-12-31 01:22
I opened a new window, and here's the contents of the browser console:

`TypeError: target is null[Learn More]  copyurlsexpert.js:491:13`

Does it matter if I'm running Firefox with `-no-remote` launch parameter?

**Comment by kashiif** [comment] 2016-12-31 01:30
I have no idea. Are you testing by installing xpi file? Since I cannot
reproduce it, would you be able to perform a little debugging :D?

Regards,
Kashif Iqbal Khan

**Comment by Keith94** [comment] 2016-12-31 01:42
Did you have something in mind for debugging?

I discovered that if I install the AMO release version, then I install the version from 2.6.0 branch, all the problems I was having are fixed, but I don't understand why.

Anyway, this feature now works as expected. I only noticed it was missing from the "Advanced Copy" dialog, in case it might be needed there. Otherwise the issue can be closed.

**Comment by Keith94** [comment] 2016-12-31 01:43
>Are you testing by installing xpi file?

Yes I am

**Comment by kashiif** [comment] 2016-12-31 01:50
It looks like you had an empty `urls.templates` file in `{profiledir}/copyurlsexpert` directory. Since the issue was not related to code, no need for debugging. But in case if you were interested, you can run an extension from the source by setting up [extension proxy file](https://developer.mozilla.org/en-US/Add-ons/Setting_up_extension_development_environment#Firefox_extension_proxy_file).

Process is

1. Install addon first time
2. close firefox
3. setup extension proxy file  to point to github clonned repo.
4. run the extension from source. You will need to restart browser every time there is a change in source.

**Comment by kashiif** [comment] 2016-12-31 01:52
>  I only noticed it was missing from the "Advanced Copy" dialog, in case it might be needed there

Hmmm, nice suggestion

**Comment by Keith94** [comment] 2016-12-31 02:08
Yeah, seems like that file was missing. I will try out the extension proxy file. Thanks for the tip!

**Closed** 2016-12-31 02:47 UTC
Labels: enhancement, in-review
